Регистрация:
<form action="<?=DIRECTORY_SEPARATOR?>User<?=DIRECTORY_SEPARATOR?>registration" method="post">
    Имя: <input type="text" name="name"> <br>
    Почта: <input type="text" name="email"> <br>
    Пароль: <input type="password" name="password1"> <br>
    Повторите пароль <input type="password" name="password2"> <br>
    <input type="submit" value="Зарегестрироваться">
</form>
<br>
<br>
Вход:
<form action="<?=DIRECTORY_SEPARATOR?>User<?=DIRECTORY_SEPARATOR?>authorization" method="post">
    Почта: <input type="text" name="email">
    Пароль:<input type="password" name="password">
    <input type="submit" value="Войти">
</form>
