<br>Добро пожаловать на наш блог<br><br>

<form enctype="multipart/form-data" action="..\html\..\Blog\pushmessage" method="post">
   Ваше сообщение: <input type="text" name="message"><br>
    Изображение <input type="file" name="image">
    <input type="submit" value="запукай">
</form>
<br>
<br>
Глобальный список сообщений:<br>
    <?php foreach ($this->messages as $posts):?>
    <div>
        <? if($this->user == ADMIN_ID): ?>
        <?php var_dump($posts['id']);?>
         <a href="..\html\..\Admin\deletemessage\?id=<?=$posts['id'];?>">Delete</a>
        <?endif;?>
        <span>Сообщение от пользователя:<?=htmlspecialchars($posts['name']);?></span><br>
        <span><?=htmlspecialchars($posts['text']);?></span><br><br>
        <? if($posts['image'] !=='netu'):?>
        <span><img src="http:\\fsdfs.loftschool\proerkt\html\images\<?=$posts['image'];?>" alt="Це картинка"></span><br><br>
        <?endif;?>
    </div>
    <?endforeach;?>


<br>
<br>
